// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_lAUkbzAnualOHLrcSLsiBVmY3r0-_I',
    appId: '1:22092811034:web:3a5e7f0009ad6984befaa3',
    messagingSenderId: '22092811034',
    projectId: 'paji-surwcz',
    authDomain: 'paji-surwcz.firebaseapp.com',
    storageBucket: 'paji-surwcz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJ4LBkGnThLI2bTftPnGOEjHARv0f0GY',
    appId: '1:22092811034:android:9198a78df07a6e1abefaa3',
    messagingSenderId: '22092811034',
    projectId: 'paji-surwcz',
    storageBucket: 'paji-surwcz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCAKuz0ZtpEgZrLWiTnlIgO9ilUjxAo-k',
    appId: '1:22092811034:ios:35304dccb52e030abefaa3',
    messagingSenderId: '22092811034',
    projectId: 'paji-surwcz',
    storageBucket: 'paji-surwcz.appspot.com',
    iosBundleId: 'com.example.mspbz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCAKuz0ZtpEgZrLWiTnlIgO9ilUjxAo-k',
    appId: '1:22092811034:ios:35304dccb52e030abefaa3',
    messagingSenderId: '22092811034',
    projectId: 'paji-surwcz',
    storageBucket: 'paji-surwcz.appspot.com',
    iosBundleId: 'com.example.mspbz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4_lAUkbzAnualOHLrcSLsiBVmY3r0-_I',
    appId: '1:22092811034:web:dba20aa8b32f8880befaa3',
    messagingSenderId: '22092811034',
    projectId: 'paji-surwcz',
    authDomain: 'paji-surwcz.firebaseapp.com',
    storageBucket: 'paji-surwcz.appspot.com',
  );
}
